development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  database: url_shortner_dev
  user: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  database: url_shortner_test
  user: root
  password:
